import type { Cliente, Grupo } from "./tipos";

/**
 * Carteira real da Mundo Novo Café (protótipo v2 validado pelo JP +
 * planilhas enviadas pela cliente). Usada no modo demonstração;
 * quando o Supabase conectar, estes dados viram o seed do banco.
 */

export const GRUPOS_DEMO: Grupo[] = [
  {
    id: "alta-mogiana",
    nome: "Grupo Alta Mogiana",
    administracao: "mundo_novo",
    cidade: "São Sebastião do Paraíso",
    uf: "MG",
  },
  {
    id: "cerrado-mineiro",
    nome: "Grupo Cerrado Mineiro",
    administracao: "mundo_novo",
    cidade: "Patrocínio",
    uf: "MG",
  },
  {
    id: "expocaccer",
    nome: "Expocaccer",
    administracao: "terceiro",
    nomeAdministrador: "Expocaccer (cooperativa)",
    cidade: "Patrocínio",
    uf: "MG",
  },
];

export const CLIENTES_DEMO: Cliente[] = [
  {
    id: "alto-da-serra",
    grupoId: "alta-mogiana",
    nome: "Fazenda Alto da Serra",
    tipo: "fazenda",
    fase: "ativo",
    produtor: "Silvio Dutra",
    cidade: "São Sebastião do Paraíso",
    uf: "MG",
    regiao: "Sudoeste / Alta Mogiana",
    idRa: "RA-ALTO-SERRA",
    conformidade: 88,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-08-14",
      },
    ],
    contatos: [
      { nome: "Silvio Dutra", area: "proprietario", telefone: "(35) 99999-0001" },
      { nome: "Tâmara Isa da Silva", area: "ambiental" },
      {
        nome: "Winicius Baquião Dutra",
        area: "agricola",
        telefone: "(35) 99999-0002",
      },
    ],
    imoveis: [
      {
        nome: "Serra da Boa Vista",
        proprietarios: "Silvio Dutra",
        car: "SP-3547908-B4A2.C0A0.F075.4955.8CC7.7440",
        matriculas: "7323",
        areaTotalHa: 4.2038,
        areaCafeHa: 3.74,
        areaAppHa: 0,
        areaReservaHa: 0,
        talhoes: "Santo Antônio",
      },
      {
        nome: "Sítio Serra da Boa Vista",
        proprietarios: "Silvio Dutra",
        car: "SP-3547908-8473.450D.6019.45DD.953E.686B",
        matriculas: "6390",
        areaTotalHa: 9.0505,
        areaCafeHa: 6.59,
        talhoes: "São Bento",
      },
      {
        nome: "Sítio Santa Luzia",
        proprietarios: "Silvio Dutra",
        car: "MG-3164704-08A7.1857.781A.44CB.B3C4.DEAD",
        matriculas: "45266",
        areaTotalHa: 24.523,
        areaCafeHa: 13.52,
        areaReservaHa: 11.1745,
        talhoes: "Santa Luzia 1 e 2 / Santa Luzia SP",
      },
      {
        nome: "Sítio Alto da Serra",
        proprietarios: "Luzia Albina Baquião Dutra e Silvio Dutra",
        car: "MG-3164704-0C7D.52B3.4818.4315.A418.CED6",
        matriculas: "37626",
        areaTotalHa: 7.9763,
        areaCafeHa: 7,
        talhoes: "João / João Novo",
      },
      {
        nome: "Sítio Alto da Serra (Garagem)",
        proprietarios: "Silvio Dutra",
        car: "MG-3164704-6E05.9C43.F267.4519.BCA4.18A1",
        matriculas: "37.624 / 40.734",
        areaTotalHa: 24.5757,
        areaCafeHa: 13.47,
        areaAppHa: 0.6815,
        areaReservaHa: 6.7477,
        possuiCaptacaoAgua: true,
        talhoes: "Garagem / Mangueira / Baixada / Barracão",
      },
      {
        nome: "Sítio Serra da Boa Vista (Terezinha)",
        proprietarios: "Maria Terezinha Dutra Varo / Maria Helena",
        car: "MG-3164704-3D7E.9BDC.BFB2.410C.8BCE.870C",
        matriculas: "37629",
        areaTotalHa: 9.655,
        areaCafeHa: 0,
        areaAppHa: 0.6038,
        areaReservaHa: 9.655,
      },
      {
        nome: "Sítio Geovana",
        proprietarios: "Elenice Dutra",
        car: "MG-3164704-211D.94DD.FC6A.43EA.A86B.DE7A",
        matriculas: "37625",
        areaTotalHa: 2.0217,
        areaCafeHa: 1.4,
        talhoes: "Catuai 99",
      },
      {
        nome: "Sítio São Mateus",
        proprietarios: "Elenice Dutra",
        car: "SP-3547908-8209.8B0E.FCE3.4480.93BE.9868",
        matriculas: "7325",
        areaTotalHa: 7.7688,
        areaCafeHa: 3.38,
        talhoes: "Iapar / Arara / Rubi",
      },
      {
        nome: "Nossa Senhora Aparecida",
        proprietarios: "Adriana Martins Lana Dutra / Carter Dutra",
        car: "MG-3164704-FAA4.347D.33F9.4A89.A60D.7EFF",
        matriculas: "45267",
        areaTotalHa: 8.4181,
        areaCafeHa: 6.52,
        areaAppHa: 0.4109,
        areaReservaHa: 1.3978,
        possuiCaptacaoAgua: true,
        talhoes: "Nossa Senhora Aparecida",
      },
      {
        nome: "Sítio Santa Inês",
        proprietarios: "Maria Inês Dutra",
        car: "SP-3547908-069B88894447402E975CA213E7E6E",
        matriculas: "7324",
        areaTotalHa: 5.96,
        areaCafeHa: 4,
        areaReservaHa: 1.49,
        talhoes: "Santa Inês 1 e 2",
      },
      {
        nome: "Sítio Tabuleiro",
        proprietarios: "Tâmara Isa da Silva / Winicius Baquião Dutra",
        car: "SP-3547908-6DEE.6B91.AD2B.46C4.A975.51CE",
        matriculas: "8758",
        areaTotalHa: 3.0677,
        areaCafeHa: 2.6,
        areaReservaHa: 0.193,
        talhoes: "Tabuleiro",
      },
    ],
  },
  {
    id: "bernardes",
    grupoId: "cerrado-mineiro",
    nome: "Fazenda Bernardes",
    tipo: "fazenda",
    fase: "ativo",
    cidade: "Patrocínio",
    uf: "MG",
    regiao: "Cerrado Mineiro",
    conformidade: 94,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2027-05-29",
      },
      { norma: "quatro_c", certificadora: "4C Services", status: "ativa" },
    ],
  },
  {
    id: "cedro",
    grupoId: "cerrado-mineiro",
    nome: "Fazenda Cedro",
    tipo: "fazenda",
    fase: "ativo",
    cidade: "Serra do Salitre",
    uf: "MG",
    regiao: "Cerrado Mineiro",
    conformidade: 79,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-08-14",
      },
    ],
  },
  {
    id: "chapadao-de-ferro",
    grupoId: "cerrado-mineiro",
    nome: "Fazenda Chapadão de Ferro",
    tipo: "fazenda",
    fase: "ativo",
    cidade: "Guimarânia",
    uf: "MG",
    regiao: "Cerrado Mineiro",
    conformidade: 71,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-08-14",
      },
    ],
  },
  {
    id: "lagoinha",
    grupoId: "cerrado-mineiro",
    nome: "Fazenda Lagoinha",
    tipo: "fazenda",
    fase: "ativo",
    cidade: "Pedrinópolis",
    uf: "MG",
    regiao: "Cerrado Mineiro",
    conformidade: 85,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-08-14",
      },
    ],
  },
  {
    id: "lambari",
    grupoId: "cerrado-mineiro",
    nome: "Fazenda Lambari",
    tipo: "fazenda",
    fase: "ativo",
    cidade: "Monte Carmelo",
    uf: "MG",
    regiao: "Cerrado Mineiro",
    conformidade: 90,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-09-30",
      },
      { norma: "organico", certificadora: "IBD", status: "em_implantacao" },
    ],
  },
  {
    id: "tecoara",
    grupoId: null,
    nome: "Fazenda Tecoara",
    tipo: "fazenda",
    fase: "ativo",
    cidade: "São Sebastião do Paraíso",
    uf: "MG",
    regiao: "Sudoeste de Minas",
    conformidade: 68,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-10-12",
      },
    ],
  },
  {
    id: "guatambu",
    grupoId: "expocaccer",
    nome: "Fazendas Guatambu",
    tipo: "cadeia_suprimentos",
    fase: "ativo",
    cidade: "São Sebastião do Paraíso",
    uf: "MG",
    regiao: "Sudoeste / Alta Mogiana",
    conformidade: 76,
    certificacoes: [
      {
        norma: "ra",
        certificadora: "ALAICE",
        principal: true,
        status: "ativa",
        venceEm: "2026-11-03",
      },
    ],
  },
];
