import { chaveDia, segundaDaSemana, somarDias } from "./semana";
import type { Compromisso } from "./tipos";

/**
 * Compromissos de demonstração — usados quando o Supabase não está conectado
 * (testes e modo demonstração). São calculados a partir de "hoje", e não com
 * datas fixas, para que a agenda da semana nunca apareça vazia: há itens na
 * semana atual, na anterior, na seguinte e sem data definida.
 */
export function compromissosDemo(hoje: Date = new Date()): Compromisso[] {
  const segunda = segundaDaSemana(hoje);
  const dia = (deslocamento: number) =>
    chaveDia(somarDias(segunda, deslocamento));

  return [
    // ── Semana anterior (uma pendência atrasada que continua viva) ──────────
    {
      id: "demo-agenda-atrasada",
      tipo: "tarefa",
      titulo: "Renovar outorga de captação",
      detalhe: "Outorga do Sítio Santa Luzia vence em 30 dias.",
      clienteId: "alto-da-serra",
      clienteNome: "Fazenda Alto da Serra",
      dia: dia(-4),
      origem: "data",
      regra: "outorga_30_dias",
      concluido: false,
      href: "/painel/clientes/alto-da-serra",
    },

    // ── Semana atual ────────────────────────────────────────────────────────
    {
      id: "demo-agenda-1",
      tipo: "tarefa",
      titulo: "Conferir certificado RA",
      detalhe: "Certificado Rainforest Alliance a 60 dias do vencimento.",
      clienteId: "alto-da-serra",
      clienteNome: "Fazenda Alto da Serra",
      dia: dia(0),
      origem: "data",
      regra: "certificado_60_dias",
      concluido: false,
      href: "/painel/clientes/alto-da-serra",
    },
    {
      id: "demo-agenda-2",
      tipo: "visita",
      titulo: "Auditoria interna RA 1.4",
      detalhe: null,
      clienteId: "alto-da-serra",
      clienteNome: "Fazenda Alto da Serra",
      dia: dia(0),
      origem: null,
      regra: null,
      concluido: true,
      href: "/painel/visitas/demo-visita-1",
    },
    {
      id: "demo-agenda-3",
      tipo: "tarefa",
      titulo: "Abrir CAPA do depósito de defensivos",
      detalhe: "Não conformidade EST-1 registrada na última visita.",
      clienteId: "alto-da-serra",
      clienteNome: "Fazenda Alto da Serra",
      dia: dia(1),
      origem: "evento",
      regra: "nc_gera_capa",
      concluido: false,
      href: "/painel/clientes/alto-da-serra",
    },
    {
      id: "demo-agenda-4",
      tipo: "visita",
      titulo: "Checklist ambiental trimestral",
      detalhe: null,
      clienteId: "guatambu",
      clienteNome: "Fazendas Guatambu",
      dia: dia(1),
      origem: null,
      regra: null,
      concluido: false,
      href: "/painel/visitas/demo-visita-2",
    },
    {
      id: "demo-agenda-5",
      tipo: "tarefa",
      titulo: "Cobrar matrícula atualizada do imóvel",
      detalhe: "Documento do Sítio Tabuleiro com mais de 12 meses.",
      clienteId: "cedro",
      clienteNome: "Fazenda Cedro",
      dia: dia(2),
      origem: "data",
      regra: "matricula_12_meses",
      concluido: false,
      href: "/painel/clientes/cedro",
    },
    {
      id: "demo-agenda-6",
      tipo: "tarefa",
      titulo: "Agendar treinamento de NR-31",
      detalhe: "Turma vencida desde o mês passado.",
      clienteId: "lambari",
      clienteNome: "Fazenda Lambari",
      dia: dia(2),
      origem: "manual",
      regra: null,
      concluido: false,
      href: "/painel/clientes/lambari",
    },
    {
      id: "demo-agenda-7",
      tipo: "visita",
      titulo: "Visita técnica de acompanhamento",
      detalhe: null,
      clienteId: "bernardes",
      clienteNome: "Fazenda Bernardes",
      dia: dia(3),
      origem: null,
      regra: null,
      concluido: false,
      href: "/painel/visitas/demo-visita-3",
    },
    {
      id: "demo-agenda-8",
      tipo: "tarefa",
      titulo: "Revisar plano de ação da CAPA #127",
      detalhe: "Prazo acordado com o produtor termina nesta sexta.",
      clienteId: "guatambu",
      clienteNome: "Fazendas Guatambu",
      dia: dia(4),
      origem: "evento",
      regra: "capa_prazo",
      concluido: false,
      href: "/painel/clientes/guatambu",
    },
    {
      id: "demo-agenda-9",
      tipo: "tarefa",
      titulo: "Enviar relatório de conformidade ao grupo",
      detalhe: "Consolidado mensal do Grupo Alta Mogiana.",
      clienteId: "alta-mogiana",
      clienteNome: "Grupo Alta Mogiana",
      dia: dia(5),
      origem: "manual",
      regra: null,
      concluido: false,
      href: "/painel/clientes/alta-mogiana",
    },

    // ── Semana seguinte (a navegação "próxima" mostra conteúdo) ─────────────
    {
      id: "demo-agenda-10",
      tipo: "tarefa",
      titulo: "Coletar amostras de solo",
      detalhe: "Combinado com a equipe de campo.",
      clienteId: "tecoara",
      clienteNome: "Fazenda Tecoara",
      dia: dia(8),
      origem: "manual",
      regra: null,
      concluido: false,
      href: "/painel/clientes/tecoara",
    },
    {
      id: "demo-agenda-11",
      tipo: "visita",
      titulo: "Auditoria interna — Lagoinha",
      detalhe: null,
      clienteId: "lagoinha",
      clienteNome: "Fazenda Lagoinha",
      dia: dia(10),
      origem: null,
      regra: null,
      concluido: false,
      href: "/painel/visitas/demo-visita-4",
    },

    // ── Sem data definida (faixa abaixo da grade) ───────────────────────────
    {
      id: "demo-agenda-sem-data-1",
      tipo: "tarefa",
      titulo: "Levantar documentos de EUDR pendentes",
      detalhe: "Depende do retorno do cartório.",
      clienteId: "chapadao-de-ferro",
      clienteNome: "Fazenda Chapadão de Ferro",
      dia: null,
      origem: "manual",
      regra: null,
      concluido: false,
      href: "/painel/clientes/chapadao-de-ferro",
    },
    {
      id: "demo-agenda-sem-data-2",
      tipo: "tarefa",
      titulo: "Definir responsável pela queixa recebida",
      detalhe: "Canal de queixas — sem prazo acordado ainda.",
      clienteId: null,
      clienteNome: null,
      dia: null,
      origem: "evento",
      regra: "queixa_recebida",
      concluido: false,
      href: null,
    },
  ];
}
